# Generated by Django 6.0.2 on 2026-03-04 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_interna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vendedores/'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='pagina_interna.vendedor')),
            ],
        ),
    ]
