# Generated by Django 6.0.2 on 2026-03-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_interna', '0002_remove_vendedor_ativo_remove_vendedor_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
