# Generated by Django 6.0.2 on 2026-03-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_interna', '0004_movimentacaofinanceira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
