# Generated by Django 6.0.2 on 2026-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_interna', '0005_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
