# Generated by Django 6.0.2 on 2026-03-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_interna', '0006_cliente_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(choices=[('embalagens', 'Embalagens'), ('papelaria', 'Papelaria'), ('limpeza', 'Limpeza'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
